---
# tasks file for start_stop_ec2

- name: Get instance details
  include: get_instance_details.yml

- name: Execute action based on extra var
  include: start/start_instances.yml
  when: action == "start"