
- name: Get security group facts
  command: "python {{roles_directory}}/ec2-start-stop/files/ec2_group_facts.py {{item.id}}"
  with_items: "{{instances_details.instances|map(attribute='groups')|list|unique}}"
  register: security_groups

- set_fact:
    existing_security_group: "{{security_groups.results|map(attribute='stdout')|list|min}}"

- name: Store existing security group
  copy: content="{{existing_security_group}}" dest="{{roles_directory}}/ec2-start-stop/files/existing_security_groups_{{existing_security_group.id}}.json" mode=0644

- ec2_group:
    name: "{{ existing_security_group.name }}"
    description: "{{ existing_security_group.description }}"
    rules: "{{instances.security_group.rules}}"
    rules_egress: "{{instances.security_group.rules_egress}}"
    purge_rules: no
    purge_rules_egress: no